[package]
name = "lighthouse-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.18"
tokio = { version = "1", features = ["full"] }
rand = "0.8"
futures = "0.3"
serde_array_query = "0.3.0"
serde = { version = "1", features = ["derive"] }
warp = { git = "https://github.com/aoikurokawa/warp.git", branch = "uri-too-long" }
tracing = "0.1"
tracing-subscriber = "0.3"
hyper = { version = "0.14.27", features = ["full"] }
