[package]
name = "account-proof-geyser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = { workspace = true }
solana-geyser-plugin-interface = "1.18.4"
solana-sdk = { workspace = true }
